import test from 'node:test';
import assert from 'node:assert/strict';
import {parseProfileID,parseProjectionEpoch,emptyProjection,acceptSnapshot,applyEvent,tabIdentityKey,retainActivations,loadProfileID} from '../../../extension/dist/domain/index.js';
const p=parseProfileID('123e4567-e89b-42d3-a456-426614174000'), e=parseProjectionEpoch('123e4567-e89b-42d3-a456-426614174001');
function row(tab_id,profile_id=p,epoch=e){const tab_identity={profile_id,context_kind:'normal',tab_id};return {profile_id,context_kind:'normal',tab_identity,window_id:1,group_id:null,title_display:'t',title_search:'t',url_search:'https://example.test/',url_display:'example.test',domain_display:'example.test',domain_search:'example.test',pinned:false,active:false,eligible:true,observed_at:1,projection_epoch:epoch,projection_revision:1};}
test('ProfileID accepts only canonical lowercase UUIDv4',()=>{assert.equal(parseProfileID(String(p)),p);for(const v of ['','123e4567-e89b-12d3-a456-426614174000','123E4567-E89B-42D3-A456-426614174000'])assert.throws(()=>parseProfileID(v));});
test('snapshot partitions profile/context and atomically rejects invalid rows',()=>{const s=emptyProjection(p,'normal');assert.equal(acceptSnapshot(s,e,[row(7)]),'APPLIED');const before=[...s.records.keys()];assert.equal(acceptSnapshot(s,e,[row(8),row(9,parseProfileID('123e4567-e89b-42d3-a456-426614174002'))]),'SNAPSHOT_REQUIRED');assert.deepEqual([...s.records.keys()],before);assert.notEqual(tabIdentityKey(row(7).tab_identity),tabIdentityKey({...row(7).tab_identity,context_kind:'private'}));});
test('revision fence rejects gaps, idempotent duplicates, conflicts, stale epoch, and removal',()=>{const s=emptyProjection(p,'normal');acceptSnapshot(s,e,[row(7)]);const ev={profile_id:p,context_kind:'normal',epoch:e,sequence:2,previous_revision:1,operation:'upsert',tab_identity:row(8).tab_identity,record:row(8)};assert.equal(applyEvent(s,ev),'APPLIED');assert.equal(applyEvent(s,ev),'DUPLICATE');assert.equal(applyEvent(s,{...ev,record:row(9)}),'REVISION_MISMATCH');const rev=s.revision;assert.equal(applyEvent(s,{...ev,sequence:4,previous_revision:3}),'SNAPSHOT_REQUIRED');assert.equal(applyEvent(s,{...ev,epoch:parseProjectionEpoch('123e4567-e89b-42d3-a456-426614174003')}),'SNAPSHOT_REQUIRED');assert.equal(Number(s.revision),Number(rev));});
test('retention excludes private/future/expired and caps deterministic count',()=>{const items=Array.from({length:502},(_,n)=>({profile_id:p,context_kind:'normal',tab_identity:row(n).tab_identity,domain:'example.test',activated_at:900000000000+n,source:'keyboard_enter',storage_sequence:n}));const kept=retainActivations([...items,{...items[0],context_kind:'private'}],900000000000+501);assert.equal(kept.length,500);assert.equal(kept[0].storage_sequence,2);});
test('profile identity creates only on fresh install and never repairs missing or corrupt persisted values',async()=>{let value=null;const writes=[];const store={read:async()=>value,write:async id=>{writes.push(id);value=id},removeAfterDisconnect:async()=>{value=null}};await assert.rejects(loadProfileID(store,false),/PROFILE_ID_MISSING/);assert.equal(writes.length,0);const created=await loadProfileID(store,true);assert.match(created,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);assert.equal(await loadProfileID(store,false),created);assert.equal(writes.length,1);value='malformed';await assert.rejects(loadProfileID(store,false),/INVALID_PROFILE_ID/);assert.equal(value,'malformed');const failing={read:async()=>null,write:async()=>{throw Error('write failed')},removeAfterDisconnect:async()=>{}};await assert.rejects(loadProfileID(failing,true),/write failed/);});
