package domain

import ("encoding/json"; "errors"; "regexp"; "sort"; "unicode/utf8")

type ProfileID string
type ContextKind string
const ( ContextNormal ContextKind="normal"; ContextPrivate ContextKind="private" )
var uuidV4=regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)
func ParseProfileID(v string)(ProfileID,error){if len(v)!=36||!uuidV4.MatchString(v){return "",errors.New("INVALID_PROFILE_ID")};return ProfileID(v),nil}
type TabIdentity struct{ProfileID ProfileID `json:"profile_id"`; ContextKind ContextKind `json:"context_kind"`; TabID int64 `json:"tab_id"`}
func (i TabIdentity) Equal(o TabIdentity)bool{return i==o}
type EligibleTabRecord struct{ProfileID ProfileID `json:"profile_id"`;ContextKind ContextKind `json:"context_kind"`;TabIdentity TabIdentity `json:"tab_identity"`;WindowID int64 `json:"window_id"`;GroupID *int64 `json:"group_id"`;TitleDisplay string `json:"title_display"`;TitleSearch string `json:"title_search"`;URLSearch string `json:"url_search"`;URLDisplay string `json:"url_display"`;DomainDisplay string `json:"domain_display"`;DomainSearch string `json:"domain_search"`;Pinned bool `json:"pinned"`;Active bool `json:"active"`;Eligible bool `json:"eligible"`;ObservedAt int64 `json:"observed_at"`;ProjectionEpoch string `json:"projection_epoch"`;ProjectionRevision uint64 `json:"projection_revision"`}
func (r EligibleTabRecord) Valid(profile ProfileID,kind ContextKind,epoch string)bool{return r.ProfileID==profile&&r.ContextKind==kind&&r.TabIdentity.ProfileID==profile&&r.TabIdentity.ContextKind==kind&&r.TabIdentity.TabID>=0&&r.WindowID>=0&&r.Eligible&&r.ProjectionEpoch==epoch&&utf8.RuneCountInString(r.TitleDisplay)<=512&&utf8.RuneCountInString(r.TitleSearch)<=512&&len(r.URLSearch)<=2048&&len(r.URLDisplay)<=2048&&len(r.DomainDisplay)<=255&&len(r.DomainSearch)<=255}
type ProjectionState struct{ProfileID ProfileID;ContextKind ContextKind;Epoch string;Revision uint64;Records map[TabIdentity]EligibleTabRecord;Seen map[uint64]string}
func NewProjection(p ProfileID,k ContextKind)*ProjectionState{return &ProjectionState{ProfileID:p,ContextKind:k,Records:map[TabIdentity]EligibleTabRecord{},Seen:map[uint64]string{}}}
func(s *ProjectionState)Snapshot(epoch string,rows []EligibleTabRecord)error{if !uuidV4.MatchString(epoch)||len(rows)>10000{return errors.New("SNAPSHOT_REQUIRED")};next:=make(map[TabIdentity]EligibleTabRecord,len(rows));for _,r:=range rows{if !r.Valid(s.ProfileID,s.ContextKind,epoch){return errors.New("SNAPSHOT_REQUIRED")};if _,ok:=next[r.TabIdentity];ok{return errors.New("SNAPSHOT_REQUIRED")};next[r.TabIdentity]=r};s.Epoch=epoch;s.Revision=1;s.Records=next;s.Seen=map[uint64]string{};return nil}
type ProjectionEvent struct{ProfileID ProfileID `json:"profile_id"`;ContextKind ContextKind `json:"context_kind"`;Epoch string `json:"epoch"`;Sequence uint64 `json:"sequence"`;PreviousRevision uint64 `json:"previous_revision"`;Operation string `json:"operation"`;Identity TabIdentity `json:"tab_identity"`;Record *EligibleTabRecord `json:"record,omitempty"`}
func(s *ProjectionState)Apply(e ProjectionEvent)string{if e.ProfileID!=s.ProfileID||e.ContextKind!=s.ContextKind||e.Epoch!=s.Epoch||s.Epoch==""{return "SNAPSHOT_REQUIRED"};raw,_:=json.Marshal(e);sig:=string(raw);if old,ok:=s.Seen[e.Sequence];ok{if old==sig{return "DUPLICATE"};return "REVISION_MISMATCH"};if e.Sequence!=s.Revision+1||e.PreviousRevision!=s.Revision{return "SNAPSHOT_REQUIRED"};if e.Operation=="upsert"&&(e.Record==nil||!e.Record.Valid(s.ProfileID,s.ContextKind,s.Epoch)||e.Record.TabIdentity!=e.Identity){return "SNAPSHOT_REQUIRED"};if e.Operation=="remove"{if _,ok:=s.Records[e.Identity];!ok{return "SNAPSHOT_REQUIRED"}}else if e.Operation!="upsert"{return "SNAPSHOT_REQUIRED"};next:=make(map[TabIdentity]EligibleTabRecord,len(s.Records)+1);for k,v:=range s.Records{next[k]=v};if e.Operation=="remove"{delete(next,e.Identity)}else{next[e.Identity]=*e.Record};s.Records=next;s.Revision++;s.Seen[e.Sequence]=sig;return "APPLIED"}
type ActivationMetadata struct{ProfileID ProfileID;ContextKind ContextKind;TabIdentity TabIdentity;Domain string;ActivatedAt int64;Source string;StorageSequence uint64}
func RetainActivations(rows []ActivationMetadata,now int64)[]ActivationMetadata{out:=make([]ActivationMetadata,0,len(rows));for _,r:=range rows{if r.ContextKind==ContextNormal&&r.ActivatedAt>=now-30*86400&&r.ActivatedAt<=now{out=append(out,r)}};sort.Slice(out,func(i,j int)bool{if out[i].ActivatedAt==out[j].ActivatedAt{return out[i].StorageSequence<out[j].StorageSequence};return out[i].ActivatedAt<out[j].ActivatedAt});if len(out)>500{out=out[len(out)-500:]};return out}
